### ISSUE TITLE
[BUG] unmanaged feature is created that is not linked to the FM when saving meta and instance WF

### ISSUE THREAD

**Issue by MireilleBF** [MireilleBF/FromMLWFConfigurationToBPMN#141]
**Describe the bug**
Here is the resulting FM
![bugFM](https://user-images.githubusercontent.com/18258429/87827948-3641c000-c87c-11ea-9cfc-31b794e5908e.png)

**To Reproduce**
@Test
	@DisplayName("Test with a basic workflow adding one Step")
	public void testBasicSampleUsingCommandLine() throws ParserConfigurationException, SAXException, IOException {
		String metaWFPATH = "../BPMN-Models/BasicMetaWF.bpmn2";
		String instanceWFPATH = "../BPMN-Models/BasicWF_instance00.bpmn2";
		String sourceFM="../samples/basicFM.xml";
		//I make a copy for test
		String copiedFM= FM_OUT_PATH +"basicFM_SAVE0.xml";
		File copiedFile = new File(copiedFM);
		File sourceFile = new File(sourceFM);
		FileUtils.copyFile(sourceFile, copiedFile);
		File fin = new File(metaWFPATH);
		assertTrue(fin.exists());
		assertTrue(copiedFile.exists());

Moreover, I lost idempotence.

**Comment by NicolasLacroix** [comment]
Are you sure that it is not a refreshing issue ?

**Comment by MireilleBF** [comment]
Sure. It appears when testing idempotence with save, i.e.
1 save "../BPMN-Models/BasicMetaWFHierarchie.bpmn2"  "../BPMN-Models/instanceBasicHierarchieToFail.bpmn2";
"../samples/basicFM.xml"

And I make it again in the resulting FM.
I want the FM is not modified.
But Unmanaged task is added.
Sometime you can't see the task but it is present.

![Capture d’écran 2020-07-18 à 14 00 13](https://user-images.githubusercontent.com/18258429/87852050-05ef3580-c8ff-11ea-9ebe-c8581f9816be.png)

**Comment by MireilleBF** [comment]
The problem arises during the idempotence test for save, regardless of the files
